unifiy argument processing; enable remote calls

diff --git a/libupd b/libupd
--- a/libupd
+++ b/libupd
@@ -20,3 +20,48 @@ install_scriptlet() {
     ln -sf "../available/$(basename "$0")" "$(dirname "$(dirname "$0")")/enabled/$(basename "$0")"
   fi
 }
+
+validate() {
+  if prereq
+  then
+    echo "Prerequisites are met"
+    exit 0
+  else
+    echo "Prequisites are missing!" >&2
+    exit 1
+  fi
+}
+
+parse_args() {
+  unset MODE
+  unset RESTARTED
+  unset REMOTE
+  while [ $# -gt 0 ]
+  do
+    case "$1" in
+    -a|--all)
+      REMOTE=1
+      shift
+      ;;
+    -i|--install)
+      MODE=install
+      shift
+      ;;
+    -m|--modified)
+      RESTARTED=1
+      shift
+      ;;
+    -u|--update)
+      MODE=update
+      shift
+      ;;
+    -v|--validate)
+      MODE=validate
+      shift
+      ;;
+    *)
+      echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
+      exit 1
+    esac
+  done
+}
