Clean up scriptlets

diff --git a/available/10-apt b/available/10-apt
--- a/available/10-apt
+++ b/available/10-apt
@@ -7,15 +7,22 @@ prereq() {
 }
 
 install() {
-  require apt-get || ( echo "apt-get not found, not installing $(basename "$0")" >&2; return 1 )
-  require sudo || ( echo "sudo not found, not installing $(basename "$0")" >&2; return 1 )
-
+  if ! require apt-get
+  then
+    echo "apt-get not found, not installing $(basename "$0")" >&2
+    return 1
+  fi
+  if ! require sudo
+  then
+    echo "sudo not found, not installing $(basename "$0")" >&2
+    return 1
+  fi
   install_scriptlet
 }
 
 update() {
   echo ------ Starting apt-get ------
-  prereq || return 1
+  if ! prereq || return 1
 
   sudo apt-get update
   sudo apt-get -y full-upgrade
diff --git a/available/20-snap b/available/20-snap
--- a/available/20-snap
+++ b/available/20-snap
@@ -8,7 +8,11 @@ prereq() {
 }
 
 install() {
-  require snap || ( echo "snap not found, not installing $(basename "$0")" >&2; return 1 )
+  if ! require snap
+  then
+    echo "snap not found, not installing $(basename "$0")" >&2
+    return 1
+  fi
   install_scriptlet
 }
 
diff --git a/available/50-firmware b/available/50-firmware
--- a/available/50-firmware
+++ b/available/50-firmware
@@ -8,7 +8,11 @@ prereq() {
 }
 
 install() {
-  require fwupdmgr || ( echo "fwupdmgr not found, not installing $(basename "$0")" >&2; return 1 )
+  if ! require fwupdmgr
+  then
+    echo "fwupdmgr not found, not installing $(basename "$0")" >&2
+    return 1
+  fi
   install_scriptlet
 }
 
diff --git a/available/51-steam b/available/51-steam
--- a/available/51-steam
+++ b/available/51-steam
@@ -7,7 +7,11 @@ prereq() {
 }
 
 install() {
-  require /usr/games/steamcmd || ( echo "steamcmd not found, not installing $(basename "$0")" >&2; return 1 )
+  if ! require /usr/games/steamcmd
+  then
+    echo "steamcmd not found, not installing $(basename "$0")" >&2
+    return 1
+  fi
   install_scriptlet
 }
 
