Add granularity to scriptlet behaviors

diff --git a/available/10-apt b/available/10-apt
--- a/available/10-apt
+++ b/available/10-apt
@@ -1,21 +1,61 @@
 #!/bin/bash
 
-check_sudo
-require apt-get
+. "$(dirname "$0")/../libupd"
 
-sudo apt-get update
-sudo apt-get -y full-upgrade
-sudo apt-get -y autoremove
+prereq() {
+  check_sudo && require apt-get
+}
 
-if [ -e /var/run/reboot-required ]
-then
-  if [ -e /var/run/reboot-required.pkgs ]
+install() {
+  require apt-get || ( echo "apt-get not found, not installing $(basename "$0")" >&2; return 1 )
+  require sudo || ( echo "sudo not found, not installing $(basename "$0")" >&2; return 1 )
+
+  install_scriptlet
+}
+
+update() {
+  echo ------ Starting apt-get ------
+  prereq || return 1
+
+  sudo apt-get update
+  sudo apt-get -y full-upgrade
+  sudo apt-get -y autoremove
+
+  if [ -e /var/run/reboot-required ]
   then
-    echo "Restart required due to the following packages:"
-    sed -e 's/^/  * /' /var/run/reboot-required.pkgs
+    if [ -e /var/run/reboot-required.pkgs ]
+    then
+      echo "Restart required due to the following packages:"
+      sed -e 's/^/  * /' /var/run/reboot-required.pkgs
+    else
+      echo "Restart required due to unspecified packages."
+    fi
   else
-    echo "Restart required due to unspecified packages."
+    echo "No reboot required."
   fi
-else
-  echo "No reboot required."
-fi
+  echo ------ Finishing apt-get ------
+}
+
+case "$1" in
+  -i|--install)
+    install
+    exit
+    ;;
+  -v|--validate)
+    if prereq
+    then
+      echo "Prerequisites are met"
+      exit 0
+    else
+      echo "Prequisites are missing!" >&2
+      exit 1
+    fi
+    ;;
+  -u|--update)
+    update
+    exit
+    ;;
+  *)
+    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
+    exit 1
+esac
diff --git a/available/20-snap b/available/20-snap
--- a/available/20-snap
+++ b/available/20-snap
@@ -1,7 +1,44 @@
 #!/bin/bash
 
-check_sudo
-require snap
+. "$(dirname "$0")/../libupd"
 
-sudo snap refresh
+prereq() {
+  check_sudo
+  require snap
+}
 
+install() {
+  require snap || ( echo "snap not found, not installing $(basename "$0")" >&2; return 1 )
+  install_scriptlet
+}
+
+update() {
+  echo ------ Starting snap ------
+  prereq || return 1
+  sudo snap refresh
+  echo ------ Finishing snap ------
+}
+
+case "$1" in
+  -i|--install)
+    install
+    exit
+    ;;
+  -v|--validate)
+    if prereq
+    then
+      echo "Prerequisites are met"
+      exit 0
+    else
+      echo "Prequisites are missing!" >&2
+      exit 1
+    fi
+    ;;
+  -u|--update)
+    update
+    exit
+    ;;
+  *)
+    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
+    exit 1
+esac
diff --git a/available/50-firmware b/available/50-firmware
--- a/available/50-firmware
+++ b/available/50-firmware
@@ -1,15 +1,51 @@
 #!/bin/bash
 
-check_sudo
-require fwupdmgr
+. "$(dirname "$0")/../libupd"
 
-if sudo systemctl status fwupd &>/dev/null
-then
-  echo "Updating firmware"
-  sudo fwupdmgr refresh --force
-  sudo fwupdmgr update -y
-else
-  echo "fwupdmgr not running?" >&2
-  exit 1
-fi
+prereq() {
+  check_sudo
+  require fwupdmgr
+}
 
+install() {
+  require fwupdmgr || ( echo "fwupdmgr not found, not installing $(basename "$0")" >&2; return 1 )
+  install_scriptlet
+}
+
+update () {
+  echo ------ Starting firmware ------
+  if sudo systemctl status fwupd &>/dev/null
+  then
+    echo "Updating firmware"
+    sudo fwupdmgr refresh --force
+    sudo fwupdmgr update -y
+  else
+    echo "fwupdmgr not running?" >&2
+    return 1
+  fi
+  echo ------ Finishing firmware ------
+}
+
+case "$1" in
+  -i|--install)
+    install
+    exit
+    ;;
+  -v|--validate)
+    if prereq
+    then
+      echo "Prerequisites are met"
+      exit 0
+    else
+      echo "Prequisites are missing!" >&2
+      exit 1
+    fi
+    ;;
+  -u|--update)
+    update
+    exit
+    ;;
+  *)
+    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
+    exit 1
+esac
diff --git a/available/51-steam b/available/51-steam
--- a/available/51-steam
+++ b/available/51-steam
@@ -1,6 +1,41 @@
 #!/bin/bash
 
-require /usr/games/steamcmd
+. "$(dirname "$0")/../libupd"
 
-/usr/games/steamcmd +login anonymous +app_update +quit
+prereq() {
+  require /usr/games/steamcmd
+}
 
+install() {
+  require /usr/games/steamcmd || ( echo "steamcmd not found, not installing $(basename "$0")" >&2; return 1 )
+  install_scriptlet
+}
+
+update () {
+  prereq || return 1
+  /usr/games/steamcmd +login anonymous +app_update +quit
+}
+
+case "$1" in
+  -i|--install)
+    install
+    exit
+    ;;
+  -v|--validate)
+    if prereq
+    then
+      echo "Prerequisites are met"
+      exit 0
+    else
+      echo "Prequisites are missing!" >&2
+      exit 1
+    fi
+    ;;
+  -u|--update)
+    update
+    exit
+    ;;
+  *)
+    echo "Usage: $(basename $0) -i|--install|-v|--validate|-u|--update"
+    exit 1
+esac
