Add oh-my-posh

diff --git a/available/60-ohmyposh b/available/60-ohmyposh
--- a/available/60-ohmyposh
+++ b/available/60-ohmyposh
@@ -3,36 +3,35 @@
 . "$(dirname "$0")/../libupd"
 
 prereq() {
-  require /usr/games/steamcmd
+  require /usr/local/bin/oh-my-posh
 }
 
 install() {
-  if ! require /usr/games/steamcmd
+  if ! require /usr/local/bin/oh-my-posh
   then
-    echo "steamcmd not found, not installing $(basename "$0")" >&2
+    echo "oh-my-posh not found, not installing $(basename "$0")" >&2
     return 1
   fi
   install_scriptlet
 }
 
 update() {
-  echo ------ Starting steam ------
+  echo ------ Starting oh-my-posh  ------
   prereq || return 1
-  /usr/games/steamcmd +login anonymous +app_update +quit
+  if ! oh-my-posh notice
+  then
+    curl -s https://ohmyposh.dev/install.sh | sudo bash -s
+  fi
 }
 
 parse_args "${@}"
-case "$MODE" in 
+case "$MODE" in
   install)
     install
-    exit
+    exit;
     ;;
   update)
     update
-    exit
-    ;;
-  validate)
-    validate
     exit
     ;;
   *)
@@ -40,3 +39,4 @@ case "$MODE" in
     echo "Called as: $0 ${@}"
     exit 1
 esac
+
